//  Heritages
const heritagesData = ['Akorosianisch', 'Skovländisch', 'Iruvianisch', 'Severosianisch', 'Dolchinseln', 'Tycherosianisch'];

//  Names
const namesData = {
    Akorosianisch: ['Aretha', 'Aldo', 'Amosen', 'Andrel','Acabey', 'Adella', 'Adriana', 'Adric', 
    'Aldo', 'Alyce', 'Andrel', 'Andrew','Andrine', 'Anna', 'Anwill', 
    'Arden', 'Arlyn', 'Arquo', 'Arvus', 'Ashlyn','Asle', 'Avery', 'Behnam', 
    'Bethia', 'Billy', 'Bodgan', 'Boulder', 'Brace','Brance', 'Branon', 'Brena', 
    'Bricks', 'Cadarn', 'Candra', 'Carissa','Carro', 'Casslyn', 'Catherine', 'Cavelle', 
    'Cemil', 'Clare', 'Clave','Corille', 'Craita', 'Crina', 'Cristoph', 'Cross', 'Crowl', 
    'Cyrene','Daphnia', 'Darcie', 'Darragh', 'Drav', 'Eale', 'Edlun', 'Edwarde',
    'Edwina', 'Edwin', 'Elena', 'Elisabeth', 'Elizabeth', 'Elspeth', 'Emeline', 'Erberk',
    'Evelyn', 'Faith', 'Feodore', 'Florence', 'Gabi', 'Gard', 'Gregory', 'Greta',
    'Grine', 'Grissell', 'Hanna', 'Harland', 'Harry', 'Helen', 'Helles',
    'Henning', 'Henrie', 'Hix', 'Holtz', 'Horace', 'Hortence', 'Hugo', 'Ilena',
    'Johannes', 'Jonathan', 'Josian', 'Judithe', 'Kacey', 'Kamelin', 'Kelyr',
    'Kevin', 'Kobb', 'Kristine', 'Kristoffer', 'Kristov', 'Laudius', 'Lauria',
    'Lenia', 'Lennox', 'Leo', 'Lida', 'Lizete', 'Lola', 'Lorette', 'Lucas', 'Lucella',
    'Lyall', 'Lynthia', 'Mads', 'Mara', 'Marcus', 'Margerie', 'Mariann',
    'Mark', 'Marte', 'Martha', 'Mary', 'Matilda', 'Merlin', 'Mette', 'Michael',
    'Mihail', 'Miller', 'Millicent', 'Milos', 'Mina', 'Monika', 'Morlan',
    'Myre', 'Narcus', 'Naria', 'Nathaniell', 'Noggs', 'Olivia', 'Orlan', 'Owen',
    'Patrick', 'Paul', 'Peyton', 'Phin', 'Phoebe', 'Piers', 'Piper', 'Polonia',
    'Quess', 'Rachel', 'Raphe', 'Remira', 'Renate', 'Richard', 'Riley', 'Ring',
    'Robin', 'Roethe', 'Roland', 'Salman', 'Samuel', 'Scott', 'Seth', 'Sonia',
    'Stavrul', 'Steffan', 'Stephana', 'Stephen', 'Stev', 'Susanna', 'Talitha',
    'Tesslyn', 'Thea', 'Thena', 'Theodore', 'Theophilus', 'Thomasin',
    'Timoth', 'Tobias', 'Tocker', 'Tom', 'Tommy', 'Trude', 'Veleris',
    'Veretta', 'Vestine', 'Vey', 'Volette', 'Weaver', 'Wester', 'Wil', 'Willie',
    'Willow', 'Wilmot', 'Zach', 'Zacharia', 'Branon', 'Brace', 'Brance', 'Brena', 
    'Bricks', 'Candra', 'Carissa', 'Carro', 'Casslyn', 'Cavelle', 'Clave', 'Corille', 
    'Cross', 'Crowl', 'Cyrene', 'Daphnia', 'Drav', 'Edlun', 'Emeline', 'Grine', 
    'Helles','Hix', 'Holtz', 'Kamelin', 'Kelyr', 'Kobb', 'Kristov', 'Laudius', 
    'Lauria', 'Lenia', 'Lizete', 'Lorette', 'Lucella', 'Lynthia', 'Mara', 'Milos', 
    'Morlan', 'Myre', 'Narcus', 'Naria', 'Noggs', 'Orlan', 'Phin', 
    'Polonia', 'Quess', 'Remira', 'Ring', 'Roethe', 'Sesereth', 'Sethla', 
    'Skannon', 'Stavrul', 'Stev', 'Syra', 'Talitha', 'Tesslyn', 'Thena', 'Timoth', 
    'Tocker', 'Una', 'Vaurin', 'Veleris', 'Veretta', 'Vestine', 'Vey', 'Volette', 
    'Vond', 'Weaver', 'Wester', 'Zamira', 'Isaac', 'Milo', 'Nyrix', 'Clara', 'Victoria',
    'Frederick', 'Martha', 'Auber', 'Roslyn', 'Baszo', 'Vreen', 'Declan', 'Cliff', 
    'Edlun', 'Lysa', 'Mira', 'Rollo', 'Fergusson', 'Galen', 'Galen', 'Valeria', 'Eris',
    'Wellington', 'Josephine', 'Ira'],

    Skovländisch: ['Ada','Arlyn', 'Arquo', 'Arvus', 'Ashlyn','Adric', 'Sven', 'Helga', 
    'Aaron','Åge', 'Aine', 'Aisling','Amosen', 'Aoibhe','Aoife', 'Arngunnur', 'Asbjørn', 
    'Åse', 'Åshild','Astrid', 'Audhild', 'Aushedar', 'Barry', 'Bjorn', 'Borghild',
    'Brandon', 'Brena', 'Brendan', 'Brian', 'Bronagh', 'Cadarn',
    'Cadhla', 'Caoimhe', 'Cathal', 'Cedwyn', 'Cian', 'Ciara',
    'Ciaran', 'Cliodhna', 'Clodagh', 'Colm', 'Conan', 'Cormac',
    'Cranog', 'Dagfinn', 'Dagny', 'Darragh', 'Deirdre', 'Eabha',
    'Edwina', 'Eimear', 'Einar', 'Eirin', 'Eithne', 'Emer',
    'Engilbjartur', 'Eoin', 'Fergal', 'Fionn', 'Fred', 'Frida', 'Glod',
    'Gøran', 'Grainne', 'Grete', 'Gunnar', 'Gwri', 'Gwyndaf',
    'Harald', 'Heidbjoerk', 'Helma', 'Herborg', 'Imogen', 'Inga',
    'Ingileifur', 'Jonas', 'Jørn', 'Karl', 'Kayleigh', 'Kobb', 'Kristin',
    'Lars', 'Lorcan', 'Mads', 'Magnhild', 'Mairead', 'Meabh',
    'Muirne', 'Nessa', 'Niall', 'Oddmund', 'Ofydd', 'Oisin',
    'Onagh', 'Orlaith', 'Oscar', 'Padraig', 'Ragnhild', 'Roisin',
    'Ruairi', 'Ryan', 'Shane', 'Shannon', 'Shauna', 'Sigmund',
    'Sigmunda', 'Silje', 'Sinead', 'Skannon', 'Skylar', 'Solbjørg',
    'Sven', 'Sverre', 'Sylvi', 'Torild', 'Torstein', 'Ulf', 'Vond',
    'Unafridur', 'Landbart', 'Øddlar'],

    Iruvianisch: ['Ahnav', 'Aiz', 'Amir', 'Amoud', 'Aniya', 'Anva', 'Arjun', 'Arkash', 
    'Asal', 'Ata', 'Ay', 'Ayan', 'Azara', 'Badan', 'Baya', 'Bhaskar', 'D’ruva',
    'Ekim', 'Elesh', 'Elesha', 'Elwafil', 'Esha', 'Eva', 'Evi',
    'Fahime', 'Fatma', 'Hadeja', 'Hakan', 'Hanesh', 'Haran', 'Iana', 'Iku', 'Iosif',
    'Isak', 'Isha', 'Izu', 'Jahan', 'Javeed', 'Jaya', 'Jin', 'Kahan', 'Kahara', 'Kai', 'Kan',
    'Kabir', 'Karim', 'Kavira', 'Ket', 'Keta', 'Kiara', 'Kiyanoosh', 'Kos', 'Kotar',
    'Kotara', 'Kyra', 'La’ana', 'Lasa', 'Lekat', 'Lenaya', 'Lor', 'Ma’ana', 'Marek',
    'Marit', 'Mata', 'Meriama', 'Mita', 'Mo’an', 'Muhan', 'Musa', 'Na’ava',
    'Nalan', 'Nashala', 'Nastaran', 'Nav', 'Navya', 'Nek’set', 'Niradhara', 'Niru',
    'Ozel', 'Parisa', 'Partha', 'Parvin', 'Pegah', 'Pooran', 'Rashid', 'Rahan',
    'Raja', 'Ro', 'Ro’an', 'Ruka', 'Rukon', 'S’rata', 'Sa’ana', 'Sanja', 'Sarha', 'Seda',
    'Sefa', 'Seth', 'Sethla', 'Sevra', 'Sindre', 'Su’ua', 'Subodh', 'Suhin', 'Syra',
    'Ta’amet', 'Taji', 'Tukara', 'Una', 'Urmila', 'Usa', 'Useth', 'Uta', 'Vaha',
    'Vanya', 'Vara', 'Vidvan', 'Von', 'Vondu', 'Zamira', 'Zarha', 'Jara'],

    Severosianisch: ['Abaka', 'Aljaiemur', 'Arslan', 'Ashigh', 'Batachikhan',
    'Battsetseg', 'Batukhan', 'Bayana', 'Berude', 'Bodonchar',
    'Bogarji', 'Bolormaa', 'Bora', 'Boshigt', 'Bukidai', 'Bulad',
    'Buyantu', 'Buyirugh', 'Chidukhul', 'Chimbai', 'Darbai',
    'Devet', 'Dinget', 'Dogshin', 'Dokholkhu', 'Dokuz',
    'Durraimur', 'Elbek', 'Etugen', 'Gambu', 'Ganengri', 'Geser',
    'Ghunan', 'Guchlug', 'Gughlug', 'Harghasun', 'Hujaghur',
    'Idris', 'Ilugei', 'Jakha', 'Jiguur', 'Jirandai', 'Kamala', 
    'Kael', 'Kegen','Khali', 'Khalja', 'Khan', 'Kharchu', 'Khatum', 'Khongkhai',
    'Khorchi', 'Khorihile', 'Khuril', 'Kulug', 'Medekhgui', 'Nayaga',
    'Nogai', 'Ogele', 'Sartak', 'Shigi-Qutuqu', 'Sibaguchu',
    'Sorghaghtani Beki', 'Tatatunga', 'Tebengri', 'Terbish',
    'Tsolmon', 'Tugan', 'Tumbinai', 'Turakina', 'Turi', 'Ublugh',
    'Ukuroa', 'Urepa', 'Urepo', 'Uru Pari', 'Uruanga', 'Yalavech'],

    Dolchinseln: ['Amber', 'André', 'Annette', 'Aray', 'Axiell', 'Bennuet',
    'Benton', 'Boldizsar', 'Brione', 'Canard', 'Cantrice', 'Caryne',
    'Coralin', 'Damon', 'Dandras', 'Daniel', 'Darnay', 'Dedrian',
    'Delmar', 'Della', 'Deven', 'Dewan', 'Elain', 'Ennis', 'Esme', 'Garlan',
    'Garon', 'Guyton', 'Jamarr', 'Jamile', 'Jarel', 'Jimarcus',
    'Kalman', 'Kaynard', 'Kea', 'Keisha', 'Khenan', 'Kenard', 'Keyon',
    'Kieran', 'Kordell', 'Lamar', 'Laran', 'Larent', 'Larice', 'Larmar',
    'Laron', 'Lorette', 'Malene', 'Marton', 'Montrose', 'Nandor',
    'Nikkya', 'Noriel', 'Nyesha', 'Odrienne', 'Odrienne', 'Oliviel', 'Ramell',
    'Rashard', 'Sakine', 'Seanne', 'Serek', 'Shalese', 'Shannel',
    'Shantair', 'Shantese', 'Sylvian', 'Taishe', 'Tameron', 'Teillan',
    'Temil', 'Tiguent', 'Trejean', 'Trinne', 'Tyshell', 'Umar',
    'Valentin', 'Vantrice', 'Vaurin', 'Veleris', 'Vignerion',
    'Volette', 'Vondrier', 'Wandalyn', 'Yevette', 'Zalan', 'Zohar',
    'Zsanett'],

    Tycherosianisch: ['Ahuaiti', 'Aia', 'Aketu', 'Akona', 'Amiria', 'Anaru', 'Anewa',
    'Ani', 'Aperira', 'Arana', 'Arona', 'Ataahua', 'Atamarie',
    'Atmaca', 'Enoka', 'Erihapeti', 'Eriki', 'Eti', 'Hakina',
    'Hamuera', 'Harakoke', 'Heeni', 'Heriko', 'Hohepa',
    'Huatare', 'Imua', 'Karauna', 'Kauri', 'Kiwi', 'Lagal', 'Lemtuna',
    'Makareta', 'Makei', 'Makutu', 'Meirion', 'Mere', 'Munu',
    'Neina', 'Nepe', 'Oea', 'Oenga', 'Pahu', 'Paipa', 'Pakanga',
    'Pakeka', 'Pianga', 'Pihere', 'Pihopa', 'Pikari', 'Raharuhi',
    'Raiepe', 'Rakina Au', 'Ramarie', 'Rara', 'Raru', 'Rere', 'Taiko',
    'Taneti', 'Tapu', 'Tarore', 'Te Pura', 'Teira', 'Tereiti', 'Timoti',
    'Turi', 'Ukuroa', 'Urepa', 'Urepo', 'Uru Manau', 'Uru Pari',
    'Uruanga', 'Uruewa', 'Wai Paku', 'Waiapi', 'Watihana',
    'Wetere', 'Wihone', 'Winiata', 'Wirihana', 'Enzo']
};



const surnamesData = {
    Akorosianisch: ['Arran', 'Athanoch', 'Babington', 'Barney', 'Becker', 'Benson',
    'Berkeley', 'Bing', 'Boden', 'Booker', 'Bowman', 'Brogan', 'Clelland',
    'Clermont', 'Coleburn', 'Comber', 'Cotton', 'Cridland', 'Dalmore',
    'Danfield', 'Davenport', 'Debenham', 'Delve', 'Denbow', 'Denholm',
    'Dunvil', 'Eastaughffe', 'Farros', 'Fawcett', 'Goody', 'Grine', 'Hackney',
    'Hadlee', 'Haley', 'Harpham', 'Helker', 'Helles', 'Hilburn', 'Hurley',
    'Keel', 'Kendal', 'Kenley', 'Kimberly', 'Kinclaith', 'Knapton', 'Lancaster',
    'Landon', 'Langdon', 'Leighton', 'Lester', 'Lomond', 'Maroden',
    'Michter', 'Morriston', 'Northcott', 'Payton', 'Penderyn', 'Prichard',
    'Ramsay', 'Ridley', 'Rodney', 'Rowan', 'Sandford', 'Sevoy', 'Slane',
    'Strangford', 'Strathmill', 'Templeton', 'Tyrconnell', 'Vale', 'Welker', 
    'Arran', 'Athanoch', 'Basran', 'Boden', 'Booker', 'Bowman', 'Breakiron', 
    'Brogan', 'Clelland', 'Clermont', 'Coleburn', 'Comber', 'Daava', 'Dalmore', 
    'Danfield', 'Dunvil', 'Farros', 'Grine', 'Haig', 'Helker', 'Helles', 
    'Hellyers', 'Jayan', 'Jeduin', 'Kardera', 'Karstas', 'Keel', 'Kessarin', 
    'Kinclaith', 'Lomond', 'Maroden', 'Michter', 'Morriston', 'Penderyn', 'Prichard', 
    'Rowan', 'Sevoy', 'Skelkallan', 'Skora', 'Slane', 'Strangford', 'Strathmill', 
    'Templeton', 'Tyrconnell', 'Vale', 'Walund', 'Welker', 'Delaney', 'Digby', 
    'Ironsmith', 'Artwright','Bethelbert', 'Penderburg', 'Kellis', 'Baz', 
    'Highwater', 'Fairchild', 'Abberwick', 'Philbert', 'Wright', 'Bowmore', 'Watson',
    'Gale', 'Thorne', 'Dunlain', 'Westbury', 'Littlefield', 'Lendall', 'Ravenglass',
    'Corvus', 'Vex', 'Locke', 'Fletcher', 'Morant', 'Blackstone', 'Penderyn', 
    'Birdwhistle', 'Schönwasser'],

    Skovländisch: ['Aaby', 'Aunan', 'Bentson', 'Braaten', 'Breakiron', 'Brogan',
    'Caderyn', 'Dahling', "O'Doherty", "O'Donnell", "O'Dwyer",
    'Egner', "O'Farrell", 'Fjeld', 'Fjelde', 'Folstad', 'Fure', 'Gjerde',
    'Haig', 'Hawken', 'Horn', 'Houg', 'Ihle', 'Karstas', "O'Keeffe",
    'Kildahl', 'Kinclaith', 'Lande', 'Langseth', "O'Leary",
    'Lillegard', 'Lindahl', "O'Mahony", "McLoughlin",
    'Michaelsen', 'Nordhagen', 'Norgaard', 'Odland',
    'Ostenson', 'Oye', "O'Reilly", 'Ritland', 'Rostad', "O'Shea",
    'Sheehan', 'Skelkallan', 'Skora', 'Smedberg', 'Tanberg',
    'Thygesen', 'Tyrconnell', 'Trygg', 'Ulvestad', 'Varvik', 'Walund', 'Halfdansson'],

    Iruvianisch: ['Adarburzin', 'Akaana', 'Anixis', 'Ankhayat', 'Ankhuset', 
    'Anserekh', 'Arkhaya', 'Avrathi', 'Azu', 'Basran', 'D’har', 'Daava', 'Diala', 
    'Hakar', 'Havran', 'Jaha', 'Jayaan', 'Jeduin', 'Ka’asa', 'Kardera', 'Kessarin',
    'Khara', 'Khuran', 'Klevanu', 'Kutu', 'Maat', 'Masura', 'Nahjan', 'Nijira', 
    'Nur', 'Nushirvan', 'Nuvket', 'Saha', 'Sanaat', 'Sesereth', 'Siakaru', 'Siatu', 
    'Siketset', 'Suresh', 'Vaati', 'Yara', 'Zayana'],

    Severosianisch: ['Abakai', 'Aljaiekin', 'Arslankhu', 'Ashighal', 'Batachikhar',
    'Battsetseger', 'Batukhanar', 'Bayanala', 'Berudekh', 'Bodoncharin',
    'Bogarjin', 'Bolormaakh', 'Borachar', 'Boshigtai', 'Bukidain', 'Buladai',
    'Buyantukhanar', 'Buyirughal', 'Chidukhuler', 'Chimbaial', 'Darbaikhan',
    'Devetar', 'Dingetar', 'Dogshinur', 'Dokholkhun', 'Dokuzai', 'Durraimurin',
    'Elbekar', 'Etugenar', 'Gambul', 'Ganengrigin', 'Geseral', 'Ghunankhu',
    'Guchlugan', 'Gughlugar', 'Harghasunar', 'Hujaghurin', 'Idrisi',
    'Ilugeiger', 'Jakhar', 'Jiguurin', 'Jirandair', 'Kamalai', 'Kegenar',
    'Khalai', 'Khaljar', 'Khankhu', 'Kharchuer', 'Khatumai', 'Khongkhaigur',
    'Khorchir', 'Khorihilein', 'Khurilan', 'Kulugar', 'Medekhguier',
    'Nayagin', 'Nogaian', 'Ogelekh', 'Sartakar', 'Shigi-Qutuquar',
    'Sibaguchar', 'Sorghaghtani Bekiar', 'Tatatungar', 'Tebengrir',
    'Terbishar', 'Tsolmonar', 'Tuganar', 'Tumbinaier', 'Turakinai',
    'Turijin', 'Ublughai', 'Ukuroar', 'Urepar', 'Urepai', 'Uru Parir',
    'Uruangar', 'Yalavechar', 'Kirby'],

    Dolchinseln: ['Allen', 'Antal', 'Beard', 'Bonnet', 'Constantine', 'Crosse',
    'Dorinn', 'Dudas', 'Fabyan', 'Fehar', 'Fennel', 'Fooard', 'Clermont',
    'Furnell', 'Furtade', 'Gaspar', 'Gilbert', 'Glanville', 'Goudie',
    'Guyot', 'Hoy', 'Huet', 'Ingram', 'Kiraly', 'Kirby',
    'Lacampaigne', 'Lassels', 'Latimer', 'Legrasse', 'Lendall',
    'Malabre', 'Martin', 'Merchant', 'Minot', 'Moran', 'Morant',
    'Morley', 'Nagy', 'Nemes', 'Ogilvie', 'Ottey', 'Pandarvas',
    'Pantofflett', 'Picairn', 'Pinter', 'Poynter', 'Ravin', 'Rayner',
    'Rear', 'Renouf', 'Sandor', 'Savonnett', 'Seegel', 'Speediarah',
    'Stillard', 'Tamas', 'Thwaites', 'Tierney', 'Tiffin', 'Uniack',
    'Urqhart', 'Uton', 'Vance', 'Veres', 'Victorie', 'Vineyom',
    'Vylder', 'Wignell', 'Zerue', 'Blackwood'],

    Tycherosianisch: ['Ahuaiti', 'Aia', 'Aketu', 'Akona', 'Amiria', 'Anaru', 'Anewa',
    'Ani', 'Aperira', 'Arana', 'Arona', 'Ataahua', 'Atamarie',
    'Atmaca', 'Enoka', 'Erihapeti', 'Eriki', 'Eti', 'Hakina',
    'Hamuera', 'Harakoke', 'Heeni', 'Heriko', 'Hohepa',
    'Huatare', 'Imua', 'Karauna', 'Kauri', 'Kiwi', 'Lagal', 'Lemtuna',
    'Makareta', 'Makei', 'Makutu', 'Meirion', 'Mere', 'Munu',
    'Neina', 'Nepe', 'Oea', 'Oenga', 'Pahu', 'Paipa', 'Pakanga',
    'Pakeka', 'Pianga', 'Pihere', 'Pihopa', 'Pikari', 'Raharuhi',
    'Raiepe', 'Rakina Au', 'Ramarie', 'Rara', 'Raru', 'Rere', 'Taiko',
    'Taneti', 'Tapu', 'Tarore', 'Te Pura', 'Teira', 'Tereiti', 'Timoti',
    'Turi', 'Ukuroa', 'Urepa', 'Urepo', 'Uru Manau', 'Uru Pari',
    'Uruanga', 'Uruewa', 'Wai Paku', 'Waiapi', 'Watihana',
    'Wetere', 'Wihone', 'Winiata', 'Wirihana']
};


//  Alter
const ageWeightsData = {
    '0-8': 0.02,
    '9-12': 0.05,
    '13-16': 0.05,
    '17-22': 0.05,
    '23-26': 0.17,
    '27-35': 0.18,
    '36-45': 0.18,
    '46-55': 0.10,
    '56-65': 0.05,
    '66-75': 0.06,
    '76-85': 0.05,
    '86-95': 0.03,
    '96-105': 0.01
};


//  Class Verteilung
const classWeightsData = {
    Proletariat: 0.7,
    Bourgeoisie: 0.25,
    Aristokratie: 0.05
};


//  Features
const featuresData = ['Groß', 'Lieblich', 'Verwittert', 'Gemeißelt', 
'Gutaussehend', 'Sportlich', 'Schlank', 'Klein', 'Entstellt, Verstümmelt', 
'Dunkel', 'Hell', 'Groß', 'Sexy', 'Brille, Prothese, Monokel', 'Verkrüppelt', 
'Stämmig', 'Wild', 'Langes Haar, Bart, Perücke', 'Zart, Elegant', 
'Kahlgeschoren, Kahl', 'Narben, Bucklig', 'Tätowiert', 'Knochig', 'Abgenutzt', 
'Rau', 'Füllig', 'Drahtig', 'Auffällig', 'Niedlich', 'Einfach', 'Alt', 'Jung', 
'Stilvoll', 'Seltsam'];



//  Clothing
const categoriesData = ['Kopfbedeckung', 'Oberteile', 'Mäntel/Oberbekleidung', 'Rüstung', 'Beinbekleidung', 'Schuhe', 'Accessoires'];

const fullSetsData = {
    Proletariat: ['Arbeiteroveralls', 'Schürzenkleid', 'Einfaches Langkleid', 'Zerrissener Anzug', 
    'Kittel', 'Matrosenanzug', 'Bauerntracht', 'Verblasstes Ballkleid', 'Sträflingskleidung', 
    'Fischeruniform', 'Arbeiterkittel', 'Bettlerkleidung', 'Schusteranzug', 'Mühlentracht', 
    'Stallkleidung', 'Kinderbettlertracht', 'Einfacher Morgenmantel', 'Schlafrock', 
    'Veraltetes Hochzeitskleid', 'Kohlenarbeiteranzug', 'Verwitterter Poncho', 'Straßenkind-Outfit', 
    'Schornsteinfegeruniform', 'Handlangerkleidung', 'Wäscherinkleidung', 'Lederhosen', 
    'Küchenhilfeuniform', 'Minenarbeiteranzug', 'Markthändlertracht', 'Kutscheruniform'],

    Bourgeoisie: ['Herrenanzug mit Weste', 'Lange Ballkleider mit Seidenkorsett', 
    'Tagkleid mit hohem Kragen', 'Hosenanzug für Damen','Tageskleid mit Stickereien', 
    'Alte Paradeuniform', 'Damenkleider mit Spitzenrüschen', 'Gehrock', 
    'Reitanzug', 'Abendkleid mit langen Handschuhen', 'Seidenpyjaman', 
    'Hosenanzug mit Weste', 'Opernkleidung', 'Offiziersuniform', 'Kleider mit Samtapplikationen', 
    'Frack', 'Anzüge mit gestreiften Mustern', 'Hochgeschlossenes Spitzenkleid', 
    'Kleider mit Perlenschmuck', 'Morgenmäntel aus Seide', 
    'Gesellschaftskleidung mit Broschen', 'Anzüge mit goldenen Manschettenknöpfen', 
    'Tanzkleidung mit Schleppen', 'Samtanzüge', 'Reisekleidung', 
    'Nachtgewänder aus feinstem Leinen'],

    Aristokratie: ['Frack mit langem Schwalbenschwanz', 'Ballkleid mit Schleppe', 
    'Militäruniform mit Medaillen', 'Samt-Abendanzug', 'Opulente Robe mit Goldverzierungen', 
    'Morgenmantel aus schwerer Seide', 'Geschneiderter Smoking', 'Rüschenhemd mit hoch tailliertem Rock', 
    'Offiziersuniform mit Epauletten', 'Gala-Robe', 'Lange, drapierte Toga', 'Spitzenunterkleid mit Korsett',
    'Lange Gewänder mit Stickerei', 'Handgemachte Brokatweste mit Kniehosen', 'Samt und Satin Abendkleid',
    'Edle Nachthemden aus Seide', 'Badeanzug', 'Elegant gesteppte Reitrüstung', 'Samtcape mit Kapuze', 
    'Festliche Gewänder mit Familiensiegel', 'Korsettkleid mit ausgestelltem Rock', 
    'Mondäner Theatersmoking', 'Opernrobe mit langen Handschuhen', 'Galauniform des Marineoffiziers', 
    'Dunkle, edle Ritualgewänder']
};



const classBasedItemsData = {
    Proletariat: {
        'Kopfbedeckung': ['Flache Kappe', 'Gestrickte Mütze', 'Alte Haube', 
        'Bandana', 'Arbeiterhut', 'Fischerhut', 'Einfaches Kopftuch', 
        'Abgenutzter Zylinder', 'Sonnenschirmmütze', 'Schornsteinfegerhut',
        'Barett', 'Strohhut', 'Kinderkappe', 'Verwitterter Fedora', 
        'Pilgerhut', 'Schlafmütze', 'Bettlerkapuze', 
        'Wollhaube', 'Alte Militärkappe','Armeekappe', 'Mühllershut', 
        'Kochmütze', 'Lederkappe', 'Bauerntuch', 'Tüllhaube', 'Gestrickte Baskenmütze', 
        'Kapuzenschal', 'Wäscherinhut', 'Dreispitz', 'Kapuze und Schleier', 'Strickmütze'],

        'Oberteile': ['Wollpullover', 'Baumwollhemd', 'Gestricktes Oberteil', 
        'Zerrissene Weste', 'Verblasstes Hemd', 'Einfache Weste', 'Einfacher Pullover', 
        'Grobes Hemd', 'Leinenbluse',  'Einfaches Korsett', 'Arbeiterweste', 'Strickjacke', 'Dunkles Oberteil', 
        'Gestrickter Poncho', 'Lederhemd', 'Baumwolltunika', 'Wolltunika', 'Arbeitshemd', 
        'Lange Weste', 'Gesteppte Jacke', 'Baumwolljacke', 'Hafenanarbeiter-Hemd', 
        'Strassenkehrer-Bluse', 'Kettenhemd', 'Einfache Bluse', 
        'Alter Pullover', 'Webstoffhemd', 'Schlichtes Top', 'Zerschlissenes Hemd', 
        'Gestrickter Pullover', 'Einfache Bluse', 'Alte Weste', 'Wolljacke', 
        'Abgenutzte Tunika', 'Patchwork-Pullover', 'Verwittertes Hemd', 'Strickweste', 
        'Einfache Jacke', 'Verblasstes Oberteil', 'Schlichtes Hemd', 'Einfacher Pullover',
        'Dunkles Hemd', 'Rissige Jacke', 'Zerschlissene Weste', 'Baumwollbluse',
        'Verwitterte Jacke', 'Lederweste', 'Graues Hemd', 'Patchwork-Jacke', 
        'Schlichte Weste', 'Einfache Tunika', 'Grobe Bluse'],

        'Mäntel/Oberbekleidung': ['Dünner Mantel', 'Zerrissener Übermantel', 
        'Wollmantel', 'Langer Schal', 'Staubiger Umhang', 'Grauer Übermantel', 
        'Einfacher Poncho', 'Baumwollmantel', 'Lederjacke', 'Verblasster Mantel', 
        'Gestrickter Umhang', 'Robuster Übermantel', 'Dunkler Mantel', 'Alter Trenchcoat', 
        'Webstoffjacke', 'Fischerjacke', 'Metallarbeiter-Mantel', 'Leichter Übermantel', 
        'Schwerer Wollmantel', 'Einfacher Umhang', 'Alte Jacke', 'Wetterfester Mantel', 
        'Hafenanarbeiter-Jacke', 'Verschmutzter Umhang', 'Einfacher Schal', 
        'Kurzer Mantel', 'Gesteppter Mantel', 'Schwerer Lederumhang','Zerschlissenes Cape',
        'Zerschlissener Mantel', 'Einfacher Umhang', 'Patchwork-Übermantel', 
        'Abgenutzter Schal', 'Wollumhang', 'Alte Jacke', 'Verwitterter Mantel', 
        'Einfacher Wollmantel', 'Dunkler Übermantel', 'Abgetragener Übermantel', 
        'Einfacher Schal', 'Lederübermantel', 'Grauer Mantel', 'Schlichter Umhang', 
        'Abgenutzte Jacke', 'Rauer Übermantel', 'Dunkler Schal', 'Gestopfter Mantel', 
        'Alte Weste', 'Gestrickter Umhang', 'Flickendecke als Umhang', 'Einfache Lederjacke', 
        'Wollschal', 'Langer Schal', 'Patchwork-Jacke', 'Alte Lederjacke', 
        'Einfacher Poncho', 'Verwitterte Weste', 'Langer Mantel', 'Kurzer Umhang', 'Kapuzenmantel'],

        'Rüstung': ['Lederarmschienen', 'Rostige Schulterplatten', 'Einfacher Brustpanzer', 
        'Metallarmschützer', 'Abgenutzte Knieschützer', 'Stahlhandschuhe', 'Verwitterter Helm', 
        'Lederpanzer', 'Bettlerarmschienen', 'Stahlbeinschützer', 'Einfacher Lederhelm', 
        'Rostige Handschuhe', 'Kettenweste', 'Abgetragene Beinschienen', 'Verwitterter Brustpanzer', 
        'Schlichter Beinpanzer', 'Handgemachte Armschützer', 'Stahlhelm', 'Abgenutzter Lederpanzer', 
        'Einfache Stahlschulterplatten', 'Kettenhandschuhe', 'Rostige Beinschützer', 
        'Lederbeinschienen', 'Einfache Armpolster', 'Kettenhelm', 'Schlichte Lederhandschuhe', 
        'Stahlweste', 'Einfacher Lederkragen'],

        'Beinbekleidung': ['Zerrissene Hosen', 'Flickwerkrock', 'Leder-Knieschoner', 
        'Alte Jeans', 'Einfache Baumwollhosen', 'Wollhosen', 'Arbeiterhosen', 
        'Kurze Hosen', 'Gepolsterte Hosen', 'Stoffrock', 'Einfache Hose', 
        'Hosen mit Flicken', 'Grobe Hosen', 'Wollrock', 'Schwere Hosen', 
        'Sackleinenhose', 'Kurzer Rock', 'Gepolsterte Hose', 'Ledershorts', 
        'Langer Rock', 'Dreckige Hose', 'Hosen mit Taschen', 'Kurze Baumwollhose', 
        'Zerschlissene Hosen', 'Einfache Baumwollhosen', 'Patchwork-Rock', 
        'Verwitterte Jeans', 'Einfache Hosen', 'Alte Leggings', 'Wollhosen', 
        'Rissige Hosen', 'Straßenjeans', 'Schlichter Rock', 'Abgenutzte Hosen', 
        'Lederleggings', 'Patchwork-Hosen', 'Alte Röcke', 'Gestopfte Hosen', 
        'Schlichte Baumwollhosen','Verwitterter Rock', 'Wollrock', 'Langer Rock', 
        'Gestrickte Hosen', 'Kurze Hosen', 'Gestopfte Leggings', 'Rissiger Rock', 
        'Hosenträger'],

        'Schuhe': ['Abgetragene Stiefel', 'Geflickte Schuhe', 'Fußwickel', 
        'Lederstiefel', 'Holzschuhe', 'Schnürschuhe', 'Einfache Sandalen', 
        'Stiefel mit Stahlkappen','Schwere Arbeitsstiefel', 'Schlammige Stiefel', 
        'Arbeiterschuhe', 'Schlichte Stiefeletten', 'Lange Stiefel', 'Kurze Stiefel', 
        'Robuste Schuhe', 'Gummiarbeitsstiefel', 'Gepolsterte Stiefel', 'Arbeitsstiefeletten', 
        'Grobe Stiefeletten', 'Kurze Sandalen', 'Einfache Stiefel','Stiefel mit Schnallen', 
        'Einfache Lederstiefel', 'Gesteppte Schuhe', 'Abgenutzte Stiefel', 
        'Patchwork-Schuhe', 'Straßenschuhe', 'Zerschlissene Sandalen', 'Einfache Lederstiefel', 
        'Verwitterte Halbschuhe', 'Rissige Schuhe', 'Wollsocken mit Sandalen', 
        'Schlichte Schuhe', 'Einfache Stiefeletten', 'Graue Stiefel', 'Straßenstiefel', 
        'Patchwork-Stiefel', 'Verblasste Schuhe', 'Alte Lederhalbschuhe', 'Gestopfte Stiefel', 
        'Lederpantoffeln', 'Alte Sandalen', 'Schlichte Lederschuhe', 'Straßensandalen', 
        'Wetterfeste Stiefel', 'Abgetragene Schuhe', 'Graue Halbschuhe', 
        'Zerschlissene Stiefeletten', 'Einfache Halbschuhe'],

        'Accessoires': ['Grobe Handschuhe', 'Altes Medaillon', 'Wollschal', 
        'Rostige Brosche', 'Einfacher Ring', 'Stoffgürtel', 'Ledergürtel', 
        'Zerrissenes Bandana', 'Kettenanhänger', 'Einfache Kette', 'Tuchhalstuch', 
        'Halsband', 'Lederarmband', 'Stoffarmband', 'Holzohrring', 
        'Abgenutztes Taschentuch', 'Baumwollhandschuhe', 'Wollhandschuhe', 
        'Einfache Tasche', 'Grober Rucksack', 'Einfacher Hut', 'Arbeiterabzeichen', 
        'Stoffbrosche', 'Knochenkette', 'Einfacher Anhänger', 'Gewebter Gürtel', 
        'Schlichte Brosche', 'Knochenarmband', 'Zerschlissenes Band', 
        'Einfacher Gürtel', 'Alte Taschenuhr', 'Patchwork-Schal', 'Einfacher Anhänger', 
        'Rostige Kette', 'Lederbörse', 'Wollhandschuhe', 'Patchwork-Armreif', 
        'Grauer Schal', 'Verwittertes Armband', 'Straßenkette', 'Gewebe-Armband', 
        'Gestrickter Muff', 'Zerschlissenes Kopftuch', 'Altes Lederarmband', 
        'Verblasste Brosche', 'Einfacher Schal', 'Baumwollbandana', 'Wollmütze', 
        'Verwitterter Anhänger', 'Patchwork-Tasche', 'Rostiger Schlüsselring', 
        'Zerschlissener Gürtel', 'Alte Medaille', 'Verblasste Halskette', 
        'Straßenbrosche', 'Patchwork-Halsband', 'Krücken', 'Gehstock', 'Rollstuhl']
    },
    Bourgeoisie: {
        'Kopfbedeckung': ['Zylinderhut', 'Hut mit breiter Krempe', 
        'Samtkappe', 'Filzhut mit Feder', 'Haube mit Spitzen', 
        'Seidenschal für den Kopf', 'Haarnetz mit Perlen', 'Turban', 'Strohhüte mit Schleifen', 
        'Kopfschmuck aus Federn und Juwelen', 'Hut mit Samtband', 'Kopftucher', 
        'Hut mit Netzschleiern', 'Hut mit kleinen Vogeldekorationen', 
        'Samthaube', 'Lederhut', 'Bonnet-Hut', 'Reithelm', 'Hut mit Pailletten', 
        'Baskenmütze', 'Schiffermütze', 'Hut mit langem Schleier', 
        'Blumenhaarreifen', 'Pelzmütze', 'Hut mit Brokatdetails', 
        'Hut mit Stickereien', 'Militärhelm', 'Diadem', 'Schlafhaube', 'Dreispitz', 
        'Kapuze und Schleier', 'Strickmütze'],

        'Oberteile': ['Bluse mit hohem Kragen', 'Weste aus Samt', 'Korsett mit Stickereien', 
        'Bluse mit Rüschen und Spitze', 'Gehrock', 'Bolero aus Seide', 
        'Samtjacke', 'Weste mit Perlenschmuck', 'Oberteil mit Puffärmeln', 
        'Tunika mit Stickereien', 'Hemd mit Stickereien', 'Bluse mit Spitzenmanschetten', 
        'Jacke mit Brokatfutter', 'Weste mit Taschenuhr', 'Bluse mit gerüschtem Kragen', 
        'Smokingjacken', 'Kasack', 'Bluse aus Chiffon', 'Schal und Tücher', 'Bluse mit durchsichtigen Ärmeln', 
        'Weste mit gestepptem Muster', 'Bluse mit Bubikragen', 'Korsett mit Stahlfedern', 
        'Bluse mit Seidenkragen', 'Jacke mit Stehkragen', 'Schultertücher', 'Spitzenbolero', 
        'Gilet', 'Jacke mit goldener Verzierung'],

        'Mäntel/Oberbekleidung': ['Seidenmantel mit Stickereien', 'Trenchcoat mit Samtkragen', 
        'Pelzmantel', 'Kapuzenmantel mit Brokatfutter', 'Umhang mit goldenen Verzierungen', 
        'Mantel mit breitem Revers', 'Kurzmantel mit Pelzbesatz', 'Langer Mantel mit Taillengürtel', 
        'Umhang mit Stickereien', 'Samtmantel mit großen Knöpfen', 'Kapuzenmantel mit Lederdetails', 
        'Blazermantel mit Puffärmeln', 'Mantel mit Paillettenbesatz', 'Kurze Jacken mit Rüschen', 
        'Kapuzenmantel aus Wolle', 'Matel mit Metallschnallen', 'Gehrock mit goldenen Applikationen', 
        'Umhang mit Perlen', 'Mantel mit Fransen', 'Trenchcoat mit Seidenfutter', 'Mantel mit Spitzenärmeln', 
        'Kapuzenmantel mit Federbesatz', 'Mantel mit gestepptem Muster', 'Jacke mit Stehkragen', 
        'Samtumhang mit Seidenfutter', 'Blazermantel mit Stickereien', 'Pelzumhange', 'Mantel mit Brokatbändern', 
        'Kurze Jacke mit Samtkragen', 'Langer Umhang mit großer Kapuze', 'Langer Mantel','Kurzer Umhang', 'Kapuzenmantel'],

        'Rüstung': ['Lederarmschützer', 'Stahlschulterplatten', 
        'Lederrüstung mit Brokatdetails', 'Kettenhemd mit goldener Verzierung', 
        'Stahlkorsett', 'Armstulpen aus gehärtetem Leder', 'Rüstung mit gravierten Mustern', 
        'Brustplatte mit Samtapplikationen', 'Rüstungshandschuhe mit Spitzen', 
        'Stahlhelm mit Feder', 'Rüstungsschuhe mit Silberdetails', 'Rüstung mit Samtfutter', 
        'Ledergürtel mit Metallapplikationen', 'Stahlbeinschützer mit Lederdetails', 
        'Rüstung mit Perlendetails', 'Lederweste mit Stahlplatten', 
        'Rüstungskragen mit Stickereien', 'Lederrüstung mit goldenen Schnallen', 
        'Rüstung mit Pailletten', 'Schutzmaske', 'Stahlhandschuhe mit Samtfutter', 
        'Kettenhemd mit Silberdetails', 'Helm mit Netzschleier', 'Korsett aus gehärtetem Leder', 
        'Rüstung mit Seidenfutter', 'Stahlbeinschützer mit Stickereien', 'Rüstung mit Metallfransen', 
        'Lederbrustplatte mit Brokatdetails', 'Stahlkorsett mit Puffärmeln', 'Lederhelm mit Federschmuck'],

        'Beinbekleidung': ['Rock mit Rüschen', 'Samthose', 'Rock mit hoher Taille', 
        'Hose mit gestreiften Mustern', 'Rock mit Spitzenunterrock', 'Culottes aus Seide', 
        'Hose mit hohem Bund', 'Rock mit Stickereien', 'Hose mit Manschetten', 'Tüllrock', 
        'Gesteppte Hose', 'Rock mit Pailletten', 'Hose mit Samtstreifen', 
        'Langer Rock mit Schleppe', 'Knielange Hose mit Stickereien', 'Rock mit Korsett', 
        'Hose mit breitem Bein', 'Rock mit Pelzbesatz', 'Hose mit goldenen Knöpfen', 
        'Rock mit Seidenschleifen', 'Hose mit Lederdetails', 'Rock mit Brokatbändern', 
        'Gehschlitze-Rock', 'Hose mit Puffärmeln', 'Rock mit großen Taschen', 
        'Knielanger Rock mit Spitze', 'Hose mit hohem Kragen','Rock mit Metallapplikationen', 
        'Hosenträger'],

        'Schuhe': ['Schnürstiefel mit Absatz', 'Schuhe mit goldenen Schnallen', 
        'Stiefel mit Stickereien', 'Schuhe mit Pailletten', 'Lederstiefel mit Spitzen', 
        'Schuhe mit hohem Absatz und Riemchen', 'Stiefel mit Lederfransen', 'Schnürschuhe aus Seide', 
        'Stiefel mit Metallverzierungen', 'Schuhe mit Spitzenüberzug', 'Schnürschuhe mit Brokat', 
        'Stiefel mit hohem Schaft', 'Schuhe mit Seidenschleifen', 'Stiefeletten mit Stickereien', 
        'Schuhe mit großem Zierknopf', 'Stiefel mit Samtüberzug', 'Schuhe mit Pelzbesatz', 
        'Stiefel mit goldenen Verzierungen', 'Schuhe mit Metallspitze', 'Stiefeletten mit Seidenfutter', 
        'Schuhe mit Netzüberzug', 'Stiefel mit breitem Absatz', 'Schuhe mit Seidenbändern', 
        'Stiefeletten mit Brokatdetails', 'Schnürschuhe mit Federn', 'Stiefel mit Korsettschnürung', 
        'Schuhe mit Stickereien', 'Stiefel mit großer Schnalle'],

        'Accessoires': ['Seidenschal', 'Lederhandschuhe mit Stickereien', 'Brosche mit Juwelen', 
        'Samttasche', 'Gürtel mit goldenen Schnallen', 'Halstuch mit Rüschen', 
        'Armband mit Perlen', 'Federboa', 'Taschenuhr mit Goldkette', 'Seidenhandschuhe', 
        'Halskette mit großen Anhängern', 'Ohrringe mit Federn', 'Ringe mit großen Steinen', 
        'Manschettenknöpfe aus Gold', 'Stola aus Pelz', 'Armbänder aus Samt', 
        'Taschen mit Metallapplikationen', 'Schal mit Stickereien', 'Gürtel mit Samtschnallen', 
        'Hut mit Netzschleiern', 'Schultertücher aus Seide', 'Krawatte aus Brokat', 
        'Ohrringe mit Perlen', 'Ringe mit Siegel', 'Manschettenknöpfe mit Juwelen', 
        'Lange Halskette mit Anhängern', 'Lederarmbänder mit Schnallen', 'Schal mit Pailletten', 
        'Gürtel mit Lederfransen', 'Korsett-Gürtel mit Stickereien','Krücken', 'Gehstock', 'Rollstuhl']
    },
    Aristokratie: {
        'Kopfbedeckung': ['Federbesetzter Zylinder', 'Spitzenschleierhut', 
        'Opulente Tiara', 'Schweres Samtdiadem', 'Kapuze mit Stickerei', 
        'Eleganter Hut mit Band', 'Reich verzierte Maskerade Maske', 
        'Pelzgefütterter Ushanka', 'Beadete Haube', 'Krone mit Familiensiegel', 
        'Gestreifte Kapitänskappe', 'Militärhut mit goldener Kordel', 'Eleganter Hut mit Schleier', 
        'Gold- und Silberhaarkämme', 'Adlige Perücken mit Locken', 'Seidenkopftuch mit Brokatrand', 
        'Schwere Lederkapuze', 'Edelsteinbesetzter Stirnreif', 'Keramikmaske mit Intarsien', 
        'Gestickte Bandana', 'Gewebte Turban', 'Adlige Tricorn Hut', 'Goldschmiedearbeit Krone', 
        'Samthut mit Feder', 'Maskerade Halbmaske mit Juwelen', 'Opulente Hochzeitskrone', 
        'Langer Schleier mit Goldfaden', 'Hochgestellter, gerüschter Kragen', 'Elegante Lederhelm', 
        'Dreispitz', 'Kapuze und Schleier', 'Strickmütze'],

        'Oberteile': ['Brokatweste', 'Seidenbluse mit Rüschen', 'Edle Militärjacke', 'Samtkorsett mit Stickerei', 
        'Lange Robe aus schwerer Seide', 'Bluse mit hohem Spitzenkragen', 'Rüschenhemd mit Manschettenknöpfen', 
        'Goldverzierte Weste', 'Frack mit Samtrevers', 'Edles Cape mit Brokat', 'Kurzärmelige Seidentunika', 
        'Schultermantel mit Pelz', 'Gewebter Schal mit Goldfaden', 'Handbestickte Weste', 'Korsett mit Perlendetail', 
        'Lange Tunika mit Samtbesatz', 'Seidenbluse mit Stickerei', 'Handgemachter Kimono', 'Kurzer Bolero mit Federn', 
        'Reich verziertes Mieder', 'Opulente Stola mit Perlen', 'Elegantes Smokingjackett', 'Schwerer Seidenumhang', 
        'Frack mit Stickerei', 'Elegante Damentop mit Schleife', 'Seidenhemd mit Manschetten', 'Adlige Ritterrüstung', 
        'Hochgeschlossene Bluse mit Rüschen', 'Kurzärmliges Kleid mit Spitze'],

        'Mäntel/Oberbekleidung': ['Samtcape mit Pelz', 'Langer Mantel mit Stickerei', 'Edle Toga mit Goldfaden', 
        'Reich verziertes Cape', 'Langer, schwerer Wollmantel', 'Seidenschal mit Fransen', 'Brokatmantel mit Pelzkragen', 
        'Langer Umhang mit Kapuze', 'Kurzer Pelzmantel', 'Gesteppter Seidenmantel', 'Lange Robe mit Goldverzierungen',
        'Schwere Ritterrüstung', 'Samtmantel mit Brokat', 'Edle Reitercape',
        'Mantel mit Stickerei und Perlen', 'Langer, eleganter Trenchcoat', 'Gewebeumhang mit Goldschnur', 
        'Ledercape mit Stickerei', 'Seidenrobe mit Goldverzierungen', 'Schwarzer Mantel mit Samtrevers', 
        'Schultermantel mit Brokat', 'Langer, gefütterter Wintermantel', 'Brokatcape mit Goldschnur', 
        'Umhang mit Stickerei', 'Edler Reitermantel', 'Toga mit Goldfaden und Perlen', 'Kurzer Samtmantel', 
        'Gesteppter Umhang', 'Langer, gewebter Umhang', 'Samtmantel mit Pelz und Stickerei', 
        'Langer Mantel', 'Kurzer Umhang', 'Kapuzenmantel'],

        'Rüstung': ['Geschmiedete Brustplatte', 'Handgefertigter Lederbrustschutz', 
        'Goldverzierte Schulterplatten', 'Eleganter Helm mit Feder', 'Handgemachte Armplatten', 
        'Schwere Beinrüstung', 'Reich verzierte Handschuhe', 'Goldbeschlagene Stiefelschienen', 
        'Samtüberzogene Brustplatte', 'Opulent gestalteter Schild', 'Gold und Silber Beinschienen', 
        'Elegante Lederhandschuhe mit Platten', 'Schwere Stiefel mit Metallspitzen', 'Gesteppte Armschienen', 
        'Elegante Ritterhelm mit Feder', 'Korsett mit Metallverstärkungen', 'Opulente Rüstungsrobe', 
        'Gesteppte Beinschützer', 'Leder- und Metallmix Handschuhe', 'Brustplatte mit Familienwappen', 
        'Schwere Stiefel mit goldenen Schnallen', 'Handgefertigter Lederschild', 'Samtüberzogene Beinschienen', 
        'Goldbeschlagene Armschienen', 'Gestickter Helm', 'Elegante Brustplatte mit Perlen', 'Reich verzierte Stiefel', 
        'Gesteppte Schulterplatten', 'Goldverzierte Lederhandschuhe', 'Opulent gestalteter Rüstungsgürtel'],

        'Beinbekleidung': ['Samthosen mit Stickerei', 'Gesteppte Reithose', 'Brokatrock mit Schleppe', 
        'Handgefertigte Kniehosen', 'Lange Robe mit Goldverzierungen', 'Handgestickte Seidenhose', 
        'Eleganter Faltenrock', 'Langer, schwerer Wollrock', 'Kurzer, edler Rock mit Rüschen', 
        'Seidenhose mit Goldfaden', 'Samtüberzogene Rüstungshose', 'Gewebe Culottes mit Stickerei', 
        'Gestreifter Rock mit Spitze', 'Lange, elegante Reithose', 'Schwerer Rock mit Brokat', 'Kurzer Samtrock', 
        'Korsettrock mit Schleppe', 'Eleganter, gesteppter Rock', 'Lange Tunika mit Schlitzen', 
        'Samt und Seidenmix Hose', 'Brokatüberzogene Kniehosen', 'Langer Rock mit Rüschen', 
        'Elegante, handgemachte Stulpenhose', 'Seidenrock mit Goldfaden', 'Kurze Hose mit Goldschnur', 
        'Lange, gestreifte Culottes', 'Schwerer Rock mit Samtbordüre', 'Kniehohe Rüstungshose', 
        'Langer, fließender Rock', 'Kurzer, gewebter Rock mit Fransen', 'Hosenträger'],

        'Schuhe': ['Samtstiefel mit Goldschnur', 'Elegante Lederschuhe mit Schnalle', 'Opulent verzierte Stiefeletten', 
        'Goldbeschlagene Reitstiefel', 'Handgefertigte Seidenschuhe', 'Lange Lederstiefel mit Stickerei', 
        'Elegante Pumps mit Perlen', 'Schwere Ritterstiefel', 'Brokatüberzogene Stiefeletten', 
        'Stiefel mit Goldverzierungen', 'Opulente Ballerinas mit Juwelen', 'Lederstiefel mit Schnalle', 
        'Kniehohe Stiefel mit Stickerei', 'Elegante Herrenschuhe mit Goldschnur', 'Stiefeletten mit Spitze und Perlen', 
        'Goldbeschlagene Sandalen', 'Lange Stiefel mit Samtrevers', 'Elegante, flache Schuhe mit Schleife', 
        'Handgemachte Lederstiefel', 'Goldverzierte Pumps', 'Brokatüberzogene Ballerinas', 'Kurze Stiefel mit Goldschnur', 
        'Stiefel mit Brokat und Schnalle', 'Elegante Damenstiefel mit Stickerei', 'Seidenschuhe mit Stickerei', 
        'Lange, gesteppte Reitstiefel', 'Samtstiefel mit Stickerei', 'Lederstiefel mit Goldverzierungen', 
        'Schuhe mit Gold- und Silberfaden'],

        'Accessoires': ['Goldverzierte Handschuhe', 'Samtstola mit Stickerei', 'Reich verziertes Medaillon', 
        'Opulente Brosche mit Familiensiegel', 'Gold- und Silberarmbänder', 'Handgemachte Lederhandschuhe', 
        'Elegante Seidenhandschuhe', 'Brokatbeutel mit Goldschnur', 'Samt und Seidenmix Schal', 
        'Goldverzierte Tasche', 'Seidenschal mit Fransen', 'Lange Perlenkette', 'Goldverzierte Manschettenknöpfe', 
        'Handgemachter Lederbeutel', 'Opulente Tiara mit Juwelen', 'Goldverzierte Gürtelschnalle', 
        'Eleganter Ledergürtel', 'Samtbeutel mit Stickerei', 'Seidenhandschuhe mit Perlen', 
        'Opulente Halskette mit Medaillon', 'Gold- und Silberohrringe', 'Lederhandschuhe mit Stickerei', 
        'Samthandschuhe mit Goldverzierungen', 'Seidenschal mit Goldfaden', 'Lange, gewebte Stola', 
        'Handgemachter Ledergürtel', 'Opulent verzierte Tasche', 'Samt und Seidenmix Handschuhe', 
        'Goldverzierte Armbanduhr', 'Brokatbeutel mit Perlen', 'Krücken', 'Gehstock', 'Rollstuhl']
    }
};


//  Berufe
const professionsData = {
        Proletariat: ['Bäcker', 'Barbier', 'Künstler', 'Schmied', 
        'Brauer', 'Metzger', 'Zimmermann', 'Wagenbauer', 'Lederarbeiter', 
        'Verkäufer', 'Kerzenmacher', 'Maurer', 'Weber', 'Büroangestellter', 
        'Händler', 'Holzarbeiter', 'Schuhmacher', 'Dachdecker', 'Ziegenhirte', 
        'Fassbinder', 'Seilmacher', 'Bote', 'Landwirt', 'Teppichmacher', 
        'Seemann', 'Fahrer', 'Färber', 'Whisper','Gelehrter', 'Rail Jack', 
        'Drucker', 'Schreiber', 'Bienenhalter', 'Bauer', 'Händler',
        'Stickerin', 'Fischhändler', 'Musiker', 'Gefängniswärter', 'Kürschner', 
        'Soldat', 'Blue Coat'],

        Bourgeoisie: ['Anwalt', 'Architekt', 'Künstler', 'Autor', 
        'Vollstrecker', 'Bankier', 'Musiker', 'Kapitän', 
        'Kopfgeldjäger', 'Arzt', 'Spirit Warden', 'Uhrmacher', 
        'Journalist', 'Kurtisane', 'Entdecker', 'Blue Coat',
        'Gelehrter', 'Rail Jack', 'Schreiber', 
        'Offizier', 'Blutegeltherapeut', 'Schlosser', 'Steuerbeamter', 
        'Funkenkonstrukteur','Schatzmeister', 'Whisper', 'Komponist', 'Verwalter'],

        Aristokratie: ['Diplomat', 'Magistrat', 'Prinz', 'Leviathanjägerkapitän', 
        'Prinzessin', 'Herzog', 'Herzogin', 'Markgraf', 'Markgräfin', 
        'Graf', 'Gräfin', 'Viscount', 'Viscountess', 'Baron', 'Baronin', 
        'Graf', 'Baronet', 'Lord', 'Lady', 'Ritter', 'Sir', 'Dame', 'Kanzler', 
        'Erzherzog', 'Erzherzogin']
    };


//  Goals
    const goalsData = ["Earn for family", "Gain political power", "Seek knowledge", "Amass wealth"];



//  Traits
    const traitsData = ['Charmant', 'Kalt', 'Kavalier', 'Frech', 
    'Misstrauisch', 'Besessen', 'Schlau', 'Ruhig', 'Launisch', 'Wild', 
    'Leichtsinnig', 'Verschwiegen', 'Rücksichtslos', 'Berechnend', 
    'Trotzig', 'Gnädig', 'Einsichtsvoll', 'Unaufrichtig', 'Geduldig', 
    'Bösartig', 'Gesittet', 'Paranoid', 'Enthusiastisch', 'Elitär', 
    'Wilde', 'Kooperativ', 'Arrogant', 'Selbstbewusst', 'Eitel', 
    'Wagemutig', 'Volatile', 'Offenherzig', 'Subtil', 'Melancholisch', 
    'Rätselhaft', 'Ruhig']


    //  Interests
    const interestsData = ['Feiner Whiskey, Wein, Bier', 'Feines Essen, Restaurants', 'Feine Kleidung, Schmuck',
    'Feine Künste, Oper, Theater', 'Malerei, Zeichnen', 'Liebhaber, Romantik, Affären, Skulptur',
    'Geschichte, Legenden', 'Architektur, Möbel', 'Dichtung, Romane, Schreiben',
    'Kampf in Arenen, Duelle', 'Vergessene Götter', 'Kirche der Ekstase',
    'Pfad der Echos', 'Weinende Dame, Wohltätigkeit', 'Antiquitäten, Artefakte, Kuriositäten',
    'Pferde, Reiten', 'Gadgets, neue Technologie', 'Waffensammler',
    'Musik, Instrumente, Tanz', 'Jagd, Schießen', 'Kochen, Gärtnern',
    'Glücksspiel, Karten, Würfel', 'Naturphilosophie', 'Drogen, Essenzen, Tabak',
    'Liebhaber, Romantik, Affären', 'Partys, soziale Veranstaltungen', 'Erkundung, Abenteuer',
    'Haustiere (Vögel, Hunde, Katzen)', 'Handwerk (Lederarbeiten, etc.)', 'Schiffe, Bootfahren',
    'Politik, Journalismus', 'Arkanbücher, Rituale', 'Spektrologie, Elektroplasm',
    'Alchemie, Medizin', 'Essenzen, Alchemie', 'Dämonenkunde, Legenden',
    'Legenden vor dem Kataklysmus']



    //  Quirks
    const quirksData = ['Abergläubisch. Glaubt an Zeichen und magische Zahlen', 'Hängt sehr an der Familie',
    'Hat in eine wichtige Familie eingeheiratet', 'Nutzt die Position, um für eine andere Fraktion zu spionieren', 
    'Zurückgezogen. Zieht es vor, über Boten zu kommunizieren', 'Massive Schulden (bei Banken/Kriminellen/Familie)', 
    'Blind für die Schwächen von Freunden, Verbündeten, Familie usw.', 'Einmal hollowed, dann wiederhergestellt. Unempfindlich gegen Geister', 
    'Hat eine chronische Krankheit, die häufige Behandlung erfordert', 'Wird heimlich (offen?) vom besitzergreifenden Geist kontrolliert', 
    'Dient der Agenda eines Dämons (wissentlich oder nicht)', 'Stolz auf Erbe, Traditionen, Muttersprache', 
    'Sorgt sich um Äußerlichkeiten, Klatsch', 'Drogen-/Alkoholmissbraucher. Oft durch ihr Laster beeinträchtigt', 'Hält Position aufgrund von Erpressung',
    'Verlässt sich auf Rat anderer, um Entscheidungen zu treffen', 'Ist in Kriegsverbrechen aus dem Einheitskrieg verwickelt', 
    'Führt ein Doppelleben unter einer Tarnidentität', 'Schwarzes Schaf / Ausgestoßen von Familie oder Organisation', 
    'Im Gefängnis oder unter Hausarrest des Adels', 'Weit gereist. Verbindungen außerhalb von Doskvol',
    'Revolutionär. Verschwörungen gegen das Imperium', 'Hat Position geerbt. Verdient/will sie vielleicht nicht', 
    'Berühmtheit. Populär geworden durch Druckwerke / Lieder / Theater', 'Skandalöser Ruf (verdient oder unverdient)', 
    'Umgeben von Kriechern, Bittstellern, Gefolgsleuten', 'Makelloser Ruf. Hoch angesehen',
    'Visionär. Hat radikale Ansichten für die Zukunft', 'Verflucht, heimgesucht, von Geistern oder Dämonen belästigt', 
    'Intensive, unvernünftige Phobie oder Abscheu', 'Umfassende Bildung in allen wissenschaftlichen Bereichen', 
    'Führt ausführliche Tagebücher, Notizen, Aufzeichnungen, Hauptbücher', 'Ist einem Ideal, einer Gruppe oder einer Tradition blindlings treu',
    'Zutiefst traditionell'];


    // Methoden
    const methodsData = ['Gewalt', 'Drohungen', 'Verhandlung', 'Studium', 'Manipulation', 'Strategie',
    'Diebstahl', 'Arkane Künste', 'Handel', 'Harte Arbeit', 'Recht', 'Politik', 'Sabotage', 'Täuschung', 
    'Alchemie', 'Erpressung', 'Teamarbeit', 'Spionage', 'Chaos']


// Make data accessible from other JS files
window.dataLibrary = {
    heritages: heritagesData,
    names: namesData,
    surnames: surnamesData,
    ageWeights: ageWeightsData,
    classWeights: classWeightsData,
    features: featuresData,
    categories: categoriesData,
    fullSets: fullSetsData,
    classBasedItems: classBasedItemsData,
    professions: professionsData,
    goals: goalsData,
    traits: traitsData,
    interests: interestsData,
    quirks: quirksData,
    methods: methodsData
    

};
